#!/usr/bin/env bash
# a bash script that transfers a file from our client to server

# Usage information
usage() {
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# check is parameters are less than 4
if [ "$#" -lt 4 ]; then
  usage
  exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/
